#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    stream:
#      username: admin
#      password: admin
rabbitmq:
  queue:
    name: "test_queue"
    json:
      name: "test_json_queue"
  exchange:
    name: "test_exchange"
  routing:
    key: "test_routing_key"
    json:
      key: "test_routing_json_key"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
